
APPLICATION_NAME = '''Lexical Machine'''
APPLICATION_ICON = '''icons/LexicalMachineIcon.png'''
APPLICATION_LAUNCH_IMAGE = '''icons/LaunchImage.jpg'''

OPEN_SOURCE_FILE_ICON = ''
OPEN_SOURCE_FILE_NAME = 'Open C source file...'
OPEN_SOURCE_FILE_SHORTCUT = 'Ctrl+O'
OPEN_SOURCE_FILE_STATUS = 'Open a C source file'

OPEN_STYLE_FILE_ICON = ''
OPEN_STYLE_FILE_NAME = 'Load a style file...'
OPEN_STYLE_FILE_SHORTCUT = ''
OPEN_STYLE_FILE_STATUS = 'Load a style file'

SAVE_OUTPUT_INFO_ICON = ''
SAVE_OUTPUT_INFO_NAME = 'Save output info'
SAVE_OUTPUT_INFO_SHORTCUT = ''
SAVE_OUTPUT_INFO_STATUS = ''

SAVE_OUTPUT_FILE_ICON = ''
SAVE_OUTPUT_FILE_NAME = 'Save output file'
SAVE_OUTPUT_FILE_SHORTCUT = ''
SAVE_OUTPUT_FILE_STATUS = ''

CLOSE_SOURCE_FILE_ICON = ''
CLOSE_SOURCE_FILE_NAME = 'Close C source file...'
CLOSE_SOURCE_FILE_SHORTCUT = 'Ctrl+W'
CLOSE_SOURCE_FILE_STATUS = 'Close a C source file'

EXIT_APPLICATION_ICON = ''
EXIT_APPLICATION_NAME = 'Exit'
EXIT_APPLICATION_SHORTCUT = 'Ctrl+Q'
EXIT_APPLICATION_STATUS = 'Exit application'

RUN_LEXICAL_MACHINCE_ICON = ''
RUN_LEXICAL_MACHINCE_NAME = 'Run'
RUN_LEXICAL_MACHINCE_SHORTCUT = 'Ctrl+R'
RUN_LEXICAL_MACHINCE_STATUS = 'Run Lexical Machine'

CONFIG_STYLE_ICON = ''
CONFIG_STYLE_NAME = 'Config style...'
CONFIG_STYLE_SHORTCUT = ''
CONFIG_STYLE_STATUS = 'Configurate Style'