
APPLICATION_NAME = '''Lexical Machine'''
APPLICATION_ICON = '''icons/LexicalMachineIcon.png'''

OPEN_SOURCE_FILE_ICON = ''
OPEN_SOURCE_FILE_NAME = 'Open C source file...'
OPEN_SOURCE_FILE_SHORTCUT = 'Ctrl+O'
OPEN_SOURCE_FILE_STATUS = 'Open a C source file'

OPEN_STYLE_FILE_ICON = ''
OPEN_STYLE_FILE_NAME = 'Open style file...'
OPEN_STYLE_FILE_SHORTCUT = ''
OPEN_STYLE_FILE_STATUS = 'Open a style file'

SAVE_OUTPUT_INFO_ICON = ''
SAVE_OUTPUT_INFO_NAME = 'Save output info'
SAVE_OUTPUT_INFO_SHORTCUT = ''
SAVE_OUTPUT_INFO_STATUS = ''

SAVE_OUTPUT_FILE_ICON = ''
SAVE_OUTPUT_FILE_NAME = 'Save output file'
SAVE_OUTPUT_FILE_SHORTCUT = ''
SAVE_OUTPUT_FILE_STATUS = ''

EXIT_APPLICATION_ICON = ''
EXIT_APPLICATION_NAME = 'Exit'
EXIT_APPLICATION_SHORTCUT = 'Ctrl+Q'
EXIT_APPLICATION_STATUS = 'Exit application'
